openapi: 3.0.0
info:
  title: RDF Toolkit
  description: A toolkit containing common functions for working with RDF.
  version: 1.0.0
paths:
  /api/v1/isomorphic:
    post:
      description: Using Apache Jena, check if two RDF graphs are isomorphic.
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                graphOneData:
                  type: string
                  example: <urn:example:s> <urn:example:p> <urn:example:o> .
                graphOneFormat:
                  type: string
                  default: text/turtle
                  enum: [text/turtle, application/n-triples, application/rdf+xml, application/ld+json]
                graphTwoData:
                  type: string
                  example: <urn:example:s> <urn:example:p> <urn:example:o> .
                graphTwoFormat:
                  type: string
                  default: text/turtle
                  enum: [text/turtle, application/n-triples, application/rdf+xml, application/ld+json]
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  isomorphic:
                    type: boolean
                    example: true
        '400':
          description: Client input error
          content:
            plain/text:
              schema:
                type: string